'copy to people mirror on tags':
  script:
  - git submodule update --init
  - ls -la
  - ''
  - '# detect last tag of repo, if this build is a tag, so we can upload archive at
    the end'
  - LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
  - echo $LAST_TAG
  - LAST_TAG_REF=$(git rev-list $LAST_TAG | head -n 1)
  - echo $LAST_TAG_REF
  - VERSION=$CI_BUILD_REF
  - echo $CI_BUILD_REF
  - if [ "$LAST_TAG_REF" = "$CI_BUILD_REF" ]; then
  - VERSION=$LAST_TAG
  - fi
  - echo $VERSION
  - ''
  - '# archive, and copy it to final build dir (only for tags),'
  - if [ "$VERSION" = "$LAST_TAG" ]; then
  - '#remove previous archive (if exists)'
  - rm -f fusioninventory-for-glpi_$VERSION.tar.gz
  - ''
  - '# prepare archive'
  - git archive --format=tar --prefix=fusioninventory/ $VERSION | gzip > fusioninventory-for-glpi_$VERSION.tar.gz
  - ''
  - '# copy to mirror'
  - scp fusioninventory-for-glpi_$VERSION.tar.gz root@people.teclib.net:/home/glebouder/public_html/mirror
  - ''
  - '# fix rights'
  - ssh root@people.teclib.net chown glebouder:users /home/glebouder/public_html/mirror/fusioninventory-for-glpi_$VERSION.tar.gz
  - fi
  tags: 
  except:
  - master

