sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - GLPI=0.90/bugfixes
  - GLPI=0.85/bugfixes
#  - GLPI=master

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
    - ant
    - xsltproc

before_install:
 - cd ..
 - git clone git://github.com/glpi-project/glpi.git glpi
 - cd glpi
 - if [[ $GLPI != 'master' ]]; then git checkout -b $GLPI origin/$GLPI; fi
 - cd ..
 - mysql -u root -e "SET PASSWORD FOR 'travis'@'localhost' = PASSWORD('travis')"
 - mysql -u root -e "GRANT ALL PRIVILEGES ON glpi.* TO 'travis'@'localhost';"
 - mysql -u root -e "FLUSH PRIVILEGES;"
 - echo '<?php class DB extends DBmysql {var $dbhost = "localhost";var $dbuser = "travis";var $dbpassword= "travis";var $dbdefault = "glpi";}' > glpi/config/config_db.php
 - mv -f fusioninventory-for-glpi glpi/plugins/fusioninventory
 - composer self-update
 - ant -Dclearsavepoint='true' -Dbasedir=. -f ./glpi/plugins/fusioninventory/phpunit/build.xml composer

install:
 - composer require satooshi/php-coveralls

before_script:
  - phpenv version-name | grep ^5.[34] && echo "extension=apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; true
  - phpenv version-name | grep ^5.[34] && echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; true

script: ant -Dclearsavepoint='true' -Dbasedir=. -f ./glpi/plugins/fusioninventory/phpunit/build.xml phpunit.all

after_script:
 - cp -fr build glpi/plugins/fusioninventory/
 - cd glpi/plugins/fusioninventory/
 - composer require satooshi/php-coveralls
 - php vendor/bin/coveralls -v

