language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_install:
 - composer self-update
 - sudo apt-get update -qq
 - sudo apt-get install -qq libapache2-mod-php5 php5-cli php5-mysql php5-xmlrpc php5-xsl php5-ldap php5-json php5-intl php5-imap php5-gd php5-curl ant xsltproc
 - git clone git://github.com/fusinv/glpi.git glpi
 - sudo mkdir /var/www/fi_testsuite/
 - sudo mv glpi /var/www/fi_testsuite/glpi
 - mysql -u root -e "SET PASSWORD FOR 'travis'@'localhost' = PASSWORD('travis')"
 - mysql -u root -e "GRANT ALL PRIVILEGES ON glpi.* TO 'travis'@'localhost';"
 - mysql -u root -e "FLUSH PRIVILEGES;"
 - sudo echo '<?php class DB extends DBmysql {var $dbhost = "localhost";var $dbuser = "travis";var $dbpassword= "travis";var $dbdefault = "glpi";}' > /var/www/fi_testsuite/glpi/config/config_db.php
 - sudo mkdir /var/www/fi_testsuite/glpi/plugins/fusioninventory
 - sudo cp -r . /var/www/fi_testsuite/glpi/plugins/fusioninventory/
 - sudo chown -R travis:www-data /var/www/fi_testsuite
 - sudo chmod -R g+w /var/www/fi_testsuite

script: cd /var/www/fi_testsuite && ant -Dclearsavepoint='true' -Dbasedir=. -f ./glpi/plugins/fusioninventory/phpunit/build.xml phpunit.all

branches:
  only:
    - master
