language: php
sudo: required
dist: trusty

env:
  global:
    - GLPI=9.5/bugfixes
    - DB=mysql

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
      addons:
        mariadb: 10.2
        apt:
          packages:
            - ant
            - xsltproc
    - php: 7.1
      env: CS=true
      addons:
        mariadb: 10.3
        apt:
          packages:
            - ant
            - xsltproc
    - php: 7.2
      addons:
        mariadb: 10.3
        apt:
          packages:
            - ant
            - xsltproc
    - php: 7.3
      addons:
        apt:
          packages:
            - ant
            - xsltproc
    - php: 7.4snapshot
      addons:
        apt:
          packages:
            - ant
            - xsltproc
    - php: nightly
      addons:
        apt:
          packages:
            - ant
            - xsltproc
  allow_failures:
    - php: nightly
    - php: 7.4snapshot

before_install:
 - cd ..
 - git clone --depth=10 -b $GLPI git://github.com/glpi-project/glpi.git glpi
 - cd glpi
 - nvm install --lts=dubnium # update node to dubnium LTS version (node v10.x + npm v6.4.1)
 - bin/console dependencies install --ci
 - cd ..
 - mv -f fusioninventory-for-glpi glpi/plugins/fusioninventory
 - pushd glpi
 - mysql -u root -e 'create database glpi;'
 - bin/console db:install --no-interaction --db-name=glpi --db-user=root
 - bin/console db:update |grep -q "No migration needed." || (echo "db:update FAILED" && exit 1)
 - popd
 - ant -Dclearsavepoint='true' -Dbasedir=. -f ./glpi/plugins/fusioninventory/phpunit/build.xml composer
 - pushd glpi/plugins/fusioninventory/phpunit/
 - composer install
 - popd

before_script:
  - phpenv version-name | grep ^5.[34] && echo "extension=apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; true
  - phpenv version-name | grep ^5.[34] && echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; true
  - phpenv config-rm xdebug.ini
  - php -S localhost:8088 -t glpi > /dev/null 2>&1 &

script:
 - composer install
 - mysql -u root -e 'select version();'
 - ant -Dclearsavepoint='true' -Dbasedir=. -f ./glpi/plugins/fusioninventory/phpunit/build.xml phpunit.all
 - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then cd glpi/plugins/fusioninventory && composer install && php vendor/bin/robo --no-interaction code:cs; fi
