language: php
sudo: required
dist: xenial

env:
  global:
    - GLPI=9.5/bugfixes
    - DB=mysql

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      addons:
        mariadb: 10.2
        apt:
          packages:
            - ant
            - xsltproc
    - php: 7.3
      addons:
        mariadb: 10.3
        apt:
          packages:
            - ant
            - xsltproc
    - php: 7.4
      addons:
        mariadb: 10.3
        apt:
          packages:
            - ant
            - xsltproc
    - php: nightly
      addons:
        mariadb: 10.3
        apt:
          packages:
            - ant
            - xsltproc
  allow_failures:
    - php: nightly

before_install:
 - cd ..
# - git clone --depth=10 -b $GLPI git://github.com/glpi-project/glpi.git glpi
 - git clone git://github.com/glpi-project/glpi.git glpi
 - cd glpi
 - git checkout 821c056a6cb1b21bad83510d86c5df119e79187e
 - nvm install --lts=dubnium # update node to dubnium LTS version (node v10.x + npm v6.4.1)
 - bin/console dependencies install --composer-options="--prefer-dist --no-progress"
 - cd ..
 - mysql -u root -e "CREATE DATABASE glpi;"
 - mv -f fusioninventory-for-glpi glpi/plugins/fusioninventory
 - pushd glpi
 - bin/console db:install --no-interaction --db-name=glpi --db-user=root
 - bin/console db:update |grep -q "No migration needed." || (echo "db:update FAILED" && exit 1)
 - popd
 - ant -Dclearsavepoint='true' -Dbasedir=. -f ./glpi/plugins/fusioninventory/phpunit/build.xml composer
 - pushd glpi/plugins/fusioninventory/phpunit/
 - composer install
 - popd

before_script:
  - phpenv config-rm xdebug.ini
  - php -S localhost:8088 -t glpi > /dev/null 2>&1 &

script:
 - composer install
 - mysql -u root -e 'select version();'
 - ant -Dclearsavepoint='true' -Dbasedir=. -f ./glpi/plugins/fusioninventory/phpunit/build.xml phpunit.all
 - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.4" ]]; then cd glpi/plugins/fusioninventory && composer install && php vendor/bin/robo --no-interaction code:cs; fi
